Repository axieinfinity/ronin-dpos-contracts, pull requests merged in 2022-12, with the labels that each got.

#116 [Staking] Merge validator's 5 addresses to 3 addresses
  contracts/interfaces/staking/IBaseStaking.sol
  contracts/interfaces/staking/ICandidateStaking.sol
  contracts/ronin/staking/BaseStaking.sol
  contracts/ronin/staking/CandidateStaking.sol
  contracts/ronin/staking/DelegatorStaking.sol
  contracts/ronin/validator/CandidateManager.sol
  test/bridge/BridgeTracking.test.ts
  test/helpers/address-set-types.ts
  test/integration/ActionSlashValidators.test.ts
  test/integration/ActionSubmitReward.test.ts
  test/integration/ActionWrapUpEpoch.test.ts
  test/maintainance/Maintenance.test.ts
  test/slash/CreditScore.test.ts
  test/slash/SlashIndicator.test.ts
  test/staking/Staking.test.ts
  test/validator/RoninValidatorSet.test.ts
Labels: enhancement, New ABI

#117 [CandidateManager] Add getter for schedule of commision change
  contracts/interfaces/validator/ICandidateManager.sol
  contracts/ronin/validator/CandidateManager.sol
Labels: enhancement, New ABI

#119 [GovernanceAdmin] Fix checking expiry proposal
  contracts/extensions/sequential-governance/CoreGovernance.sol
  test/governance-admin/GovernanceAdmin.test.ts
Labels: bug

#126 Implement function emergency exit for Validators
  contracts/extensions/collections/HasValidatorContract.sol
  contracts/extensions/isolated-governance/IsolatedGovernance.sol
  contracts/extensions/isolated-governance/bridge-operator-governance/BOsGovernanceProposal.sol
  contracts/extensions/isolated-governance/bridge-operator-governance/BOsGovernanceRelay.sol
  contracts/interfaces/IRoninGovernanceAdmin.sol
  contracts/interfaces/consumers/VoteStatusConsumer.sol
  contracts/interfaces/staking/ICandidateStaking.sol
  contracts/interfaces/validator/ICoinbaseExecution.sol
  contracts/interfaces/validator/IEmergencyExit.sol
  contracts/interfaces/validator/IRoninValidatorSet.sol
  contracts/interfaces/validator/info-fragments/ICommonInfo.sol
  contracts/interfaces/validator/info-fragments/IValidatorInfo.sol
  contracts/libraries/BridgeOperatorsBallot.sol
  contracts/libraries/EmergencyExitBallot.sol
  contracts/mainchain/MainchainGovernanceAdmin.sol
  contracts/mocks/validator/MockRoninValidatorSetExtended.sol
  contracts/mocks/validator/MockValidatorSet.sol
  contracts/ronin/RoninGovernanceAdmin.sol
  contracts/ronin/staking/CandidateStaking.sol
  contracts/ronin/validator/CandidateManager.sol
  contracts/ronin/validator/CoinbaseExecution.sol
  contracts/ronin/validator/EmergencyExit.sol
  contracts/ronin/validator/RoninValidatorSet.sol
  contracts/ronin/validator/SlashingExecution.sol
  contracts/ronin/validator/storage-fragments/CommonStorage.sol
  contracts/ronin/validator/storage-fragments/JailingStorage.sol
  contracts/ronin/validator/storage-fragments/ValidatorInfoStorage.sol
  src/config.ts
  src/deploy/proxy/ronin-validator-proxy.ts
  src/deploy/ronin-governance-admin.ts
  src/script/governance-admin-interface.ts
  src/script/proposal.ts
  src/utils.ts
  test/bridge/BridgeTracking.test.ts
  test/governance-admin/GovernanceAdmin.test.ts
  test/helpers/fixture.ts
  test/helpers/ronin-validator-set.ts
  test/helpers/utils.ts
  test/integration/ActionSlashValidators.test.ts
  test/integration/ActionSubmitReward.test.ts
  test/integration/ActionWrapUpEpoch.test.ts
  test/maintainance/Maintenance.test.ts
  test/validator/ArrangeValidators.test.ts
  test/validator/EmergencyExit.test.ts
  test/validator/RoninValidatorSet.test.ts
Labels: enhancement, ABI changes, New ABI

#132 [RoninGovernanceAdmin] Expose function & store bridge operator set
  contracts/extensions/isolated-governance/bridge-operator-governance/BOsGovernanceProposal.sol
  contracts/extensions/isolated-governance/bridge-operator-governance/BOsGovernanceRelay.sol
  contracts/extensions/sequential-governance/GovernanceProposal.sol
  contracts/extensions/sequential-governance/GovernanceRelay.sol
  contracts/interfaces/IRoninGovernanceAdmin.sol
  contracts/libraries/BridgeOperatorsBallot.sol
  contracts/mainchain/MainchainGovernanceAdmin.sol
  contracts/ronin/RoninGovernanceAdmin.sol
  test/governance-admin/GovernanceAdmin.test.ts
  test/helpers/utils.ts
Labels: ABI changes, New ABI

#133 [ValidatorSet] Add details for `StakingRewardDistributed` event
  contracts/interfaces/validator/ICoinbaseExecution.sol
  contracts/ronin/validator/CoinbaseExecution.sol
  test/helpers/ronin-validator-set.ts
  test/validator/RoninValidatorSet.test.ts
Labels: ABI changes

#130 Support voting without signatures on the Ronin network
  contracts/extensions/sequential-governance/CoreGovernance.sol
  contracts/ronin/RoninGovernanceAdmin.sol
  src/script/governance-admin-interface.ts
  test/governance-admin/GovernanceAdmin.test.ts
Labels: New ABI
