Repository axieinfinity/ronin-dpos-contracts, pull requests merged in 2023-03, with the labels that each got.

#168 [Staking] Validator commission rate must not exceed 20%
  contracts/interfaces/staking/ICandidateStaking.sol
  contracts/ronin/staking/CandidateStaking.sol
  contracts/ronin/staking/Staking.sol
  contracts/ronin/validator/CoinbaseExecution.sol
  src/config.ts
  src/deploy/proxy/staking-proxy.ts
  src/utils.ts
  test/helpers/fixture.ts
  test/staking/Staking.test.ts
  test/validator/RoninValidatorSet-Candidate.test.ts
Labels: enhancement, New ABI

#170 [BridgeTracking] Redundant check of period number
  contracts/ronin/BridgeTracking.sol
Labels: clean up

#171 [ValidatorSet] Validators May Have The Wrong Block Producer Status
  contracts/ronin/validator/CoinbaseExecution.sol
Labels: bug

#176 [RoninGateway] Fix Reentrancy Attack
  contracts/ronin/RoninGatewayV2.sol
Labels: bug

#178 [Slash] Emit event for slashing bridge operator
  contracts/interfaces/slash-indicator/ISlashBridgeOperator.sol
  contracts/ronin/slash-indicator/SlashBridgeOperator.sol
  contracts/ronin/validator/CoinbaseExecution.sol
  hardhat.config.ts
  package.json
  yarn.lock
Labels: New ABI

#179 [SlashIndicator] Fix setter in bridge voting configs
  contracts/ronin/slash-indicator/SlashBridgeVoting.sol
  test/integration/Configuration.test.ts
  test/slash/SlashIndicator.test.ts
Labels: bug

#184 [ValidatorSet] Add method check bridge slashing tier-1
  contracts/interfaces/validator/info-fragments/IJailingInfo.sol
  contracts/mocks/validator/MockValidatorSet.sol
  contracts/ronin/validator/storage-fragments/JailingStorage.sol
Labels: New ABI

#180 [SlashIndicator] Improve slash double sign
  contracts/interfaces/slash-indicator/ISlashDoubleSign.sol
  contracts/mocks/MockPrecompile.sol
  contracts/mocks/MockSlashIndicatorExtended.sol
  contracts/mocks/precompile-usages/MockPCUValidateDoubleSign.sol
  contracts/precompile-usages/PCUValidateDoubleSign.sol
  contracts/ronin/slash-indicator/SlashDoubleSign.sol
  contracts/ronin/slash-indicator/SlashIndicator.sol
  contracts/ronin/slash-indicator/SlashUnavailability.sol
  src/config.ts
  src/deploy/proxy/slash-indicator-proxy.ts
  src/utils.ts
  test/helpers/encoder.ts
  test/helpers/fixture.ts
  test/helpers/governance-admin.ts
  test/precompile-usages/PrecompileUsageValidateDoubleSign.test.ts
  test/slash/SlashIndicator.test.ts
Labels: enhancement, ABI changes

#186 [Staking] Check commission rate while applying candidate
  contracts/ronin/staking/CandidateStaking.sol
Labels: edge case

#192 [ValidatorSet] Add getter for bridge slash at period. Remove batch getters.
  contracts/interfaces/validator/info-fragments/IJailingInfo.sol
  contracts/mocks/validator/MockValidatorSet.sol
  contracts/ronin/validator/storage-fragments/JailingStorage.sol
Labels: ABI changes
