Repository axieinfinity/ronin-dpos-contracts, pull requests merged in 2023-01, with the labels that each got.

#134 [Staking] Rename for clarity between pools and active pools
  contracts/interfaces/staking/IBaseStaking.sol
  contracts/interfaces/staking/ICandidateStaking.sol
  contracts/interfaces/staking/IDelegatorStaking.sol
  contracts/interfaces/staking/IRewardPool.sol
  contracts/interfaces/staking/IStaking.sol
  contracts/mocks/MockStaking.sol
  contracts/ronin/staking/BaseStaking.sol
  contracts/ronin/staking/CandidateStaking.sol
  contracts/ronin/staking/DelegatorStaking.sol
  contracts/ronin/staking/RewardCalculation.sol
  contracts/ronin/staking/Staking.sol
  contracts/ronin/validator/CoinbaseExecution.sol
  contracts/ronin/validator/EmergencyExit.sol
  contracts/ronin/validator/SlashingExecution.sol
  test/integration/ActionSlashValidators.test.ts
  test/staking/RewardCalculation.test.ts
  test/staking/Staking.test.ts
  test/validator/EmergencyExit.test.ts
  test/validator/RoninValidatorSet.test.ts
Labels: ABI changes, New ABI

#148 [RewardCalculation] Update lowest amount in period when claiming rewards
  contracts/interfaces/staking/IRewardPool.sol
  contracts/ronin/staking/RewardCalculation.sol
  test/staking/RewardCalculation.test.ts
Labels: bug, enhancement

#149 [RoninGovernanceAdmin] Update function to get bridge voter's signatures.
  contracts/extensions/isolated-governance/bridge-operator-governance/BOsGovernanceProposal.sol
  contracts/ronin/RoninGovernanceAdmin.sol
  test/governance-admin/GovernanceAdmin.test.ts
Labels: ABI changes

#156 Remove redundant check before storage assignment
  contracts/ronin/slash-indicator/CreditScore.sol
  contracts/ronin/staking/RewardCalculation.sol
Labels: clean up
